# Juliet M Wong
# HCPC (Hierarchical Clustering on Principal Components)
# following: http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/117-hcpc-hierarchical-clustering-on-principal-components-essentials/
# Wong et al. 2019 - Transcriptional profiles of early stage red sea urchins (Mesocentrotus
#franciscanus) reveal differential regulation of gene expression across
#development

install.packages(c("FactoMineR", "factoextra"))

# load packages
library (factoextra)
library (FactoMineR)

pca <- as.data.frame(prcomp(t(na.omit(v2$E)))$x)

# Compute hierarchical clustering on principal components
res.hcpc <- HCPC(pca, min=7, max=7,graph = FALSE)

# visualize the dendrogram generated by hierarchical clustering
fviz_dend(res.hcpc, 
          cex = 0.4,                     # Label size
          palette = "jco",               # Color palette see ?ggpubr::ggpar
          rect = TRUE, rect_fill = TRUE, # Add rectangle around groups
          rect_border = "jco",           # Rectangle color
          labels_track_height = 20000)      # Augment the room for labels

# visualize individuals on the principal component map and color individuals according to the cluster they belong to
fviz_cluster(res.hcpc,
             repel = TRUE,            # Avoid label overlapping
             show.clust.cent = TRUE, # Show cluster centers
             palette = "jco",         # Color palette see ?ggpubr::ggpar
             ggtheme = theme_minimal(),
             main = "Factor map"
)

# Draw a 3D plot combining the hierarchichal clustering and the factorial map using the R base function plot()
par(cex=1.5)
plot(res.hcpc, choice = "3D.map", angle=70)

# To display the original data with cluster assignments
head(res.hcpc$data.clust,10)

# display quantitative variables that describe the most each clust
res.hcpc$desc.var$quanti

# to show principal dimensions that are the most associated with clusters
res.hcpc$desc.axes$quanti

# representative individuals of each cluster can be extracted as follow
res.hcpc$desc.ind$para

